apiVersion: apps/v1
kind: Deployment
metadata:
  name: darwin
  namespace: default
spec:
  selector:
    matchLabels:
      run: darwin
  replicas: 4
  template:
    metadata:
      labels:
        run: darwin
    spec:
      containers:
      - name: darwin-container
        image: httpd

